### ISSUE TITLE
Installation custom attributes not getting update on infobip portal

### ISSUE THREAD

**Issue by akshardarji** [infobip/mobile-messaging-sdk-ios#10]
Hello

We are adding custom attributes using installation object, we require to create segment based on true or false value.

so here we are updating segment values based on **isEnable** flag. so when we are passing true or false that values not affected in infobip portal   

we are using below function to set installation value: 
```
func setInstallationConfiguration(isEnabled: Bool){
        if let installationObj = MobileMessaging.getInstallation(){
                let subscriptions = String(isEnabled ? "true" : "false")
                installationObj.customAttributes = ["segment1" : subscriptions as NSString, "segment2" : subscriptions as NSString]
                MobileMessaging.saveInstallation(installationObj) { (error) in  debugPrint(error.debugDescription ) }
        }
 }
```
Using above code value is getting update as true but later it won't be set as false. If we get value using below code then we are getting value as false but it's not reflected false values on infobip portal. 

`let Segment1_Status = MobileMessaging.getInstallation()?.customAttributes?["segment1"] as? NSString`

after passing false value above single line code getting (Segment1_Status is false) but we are not able to see false value on infobip portal as shown in screenshot.

please find screen shots [Here](https://prnt.sc/mlgc2u)     

While sending notification using segment where (segment1 is true), if we set value as false then also we got the notification from infobip. 

Kindly look into this and hope for soonest response. 

* MobileMessaging SDK version: [5.0.7]
* Xcode version: [10.1]
* Your application language: [Swift]
* Cocoapods version: [1.5.3]

**Comment by kas-kad** [comment]
Hello, thank you for the bug report. We'll fix the issue today.

**Comment by kas-kad** [comment]
Fixed now https://github.com/infobip/mobile-messaging-sdk-ios/releases/tag/5.1.8

**Comment by kavathiyamahesh** [comment]
Thank you so much for quick release.!!!

**Comment by akshardarji** [comment]
Thanks. Appreciate you for quick response and release too. 👍
