### ISSUE TITLE
Intermittent Issue: ExternalUserId not getting update on infobip portal 

### ISSUE THREAD

**Issue by akshardarji** [infobip/mobile-messaging-sdk-ios#12]
Hello

We are updating externalUserId using personalize, we require this to identify registered user on the infobip portal and based on that we are doing few installation configuration segments value changes`(value either true/false)`.   

Here we are updating externalUserId when we are trying to update that value is not reflecting in infobip portal sometimes. 

we have tried with below functions to set externalUserId value:

```
func personalizeNotification(phones: [String]?, emails: [String]?, externalUserId: String?){
        
        let userIdentity = UserIdentity(phones: phones, emails: emails, externalUserId: externalUserId)
        MobileMessaging.personalize(forceDepersonalize: true, userIdentity: userIdentity!, userAttributes: MobileMessaging.getUser(), completion: { (error) in
            guard error == nil else {
                print(error?.description ?? "")
                return
            }
        })
}
```

```
func saveUser(externalUserId: String?){
        if let userObj = MobileMessaging.getUser(){
            if userObj.externalUserId == nil {
                userObj.externalUserId = externalUserId
                MobileMessaging.saveUser(userObj) { (error) in
                guard error == nil else {
                   print(error?.description ?? "")
                   return
                }
            }
        }
}
```
Using above code, externalUserId is getting updated sometimes but sometime it is not reflecting in infobip portal and we are not getting an error if it gets failed to updated.

Kindly look into this and hope for soonest response.

* MobileMessaging SDK version: [5.2.2]
* Xcode version: [10.1]
* Your application language: [Swift]
* Cocoapods version: [1.5.3]

**Comment by kas-kad** [comment]
Hello, please note that personalization with depersonalization enabled means that another person profile will be linked to the installation, but not the same existing person changes it's externalUserId.

**Comment by akshardarji** [comment]
Hello, You are absolutely right.

Personalization with depersonalisation being set to true means that another person profile will be linked to the installation with their custom attribute and multiple person's devices can personalisation with different installations on the same externalUserId. So I think, It'll bind automatically if same externalUserId exist in portal and also it won't be conflict their installations with each one. 

Please find this two screenshot [Link1](https://prnt.sc/ntem7l) and [Link2](https://prntscr.com/ntemk1)

Now what I'm going to say, If I tried to personalize any person with their externalUserId but somehow it got failed to personalize, In that case MobileSDK should give me an error. 

That's occurred in both the platform Android and iOS so please take care of it or provide us any other way to set externalUserId and set the custom attributes code wise.

**Comment by kavathiyamahesh** [comment]
Hello @kas-kad @tjuric , Can you please take follow up on this ticket.
Thanks

**Comment by kas-kad** [comment]
@akshardarji please provide the complete report:
1. your actions, steps to reproduce with real data, parameters that you use
2. expected result
3. actual result

Thanks in advance.

**Comment by akshardarji** [comment]
@kas-kad Sure. I can provide you all the mentioned details. 

**1. Action & Parameters:**  We have `UISwitch/Toggle` to enable/ disable push notification so when we try to enable push notification first time then we have called below code:

```
MobileMessaging.withApplicationCode(AppCode, notificationType: UserNotificationType(options: [.alert, .sound, .badge]))?.start({
        })
```

Then we have prompt with alert where we have `allow / don't allow` actions for permission so while we press allow then we have called below code on the trigger of MMNotificationCenterAuthRequestFinished observer:

```
func personalizeNotification(phones: [String]?, emails: [String]?, externalUserId: String?,completions:(()->Void)?){
            
            let userIdentity = UserIdentity(phones: phones, emails: emails, externalUserId: externalUserId)
            MobileMessaging.personalize(forceDepersonalize: true, userIdentity: userIdentity!, userAttributes: MobileMessaging.getUser(), completion: { (error) in
                guard MobileMessaging.getUser()?.externalUserId != nil || error == nil else {
                    debugPrint(error.debugDescription)
                    return
                }
                completions?()
            })
        }
```

So we are personalise with userIdentify (we are providing externalUserId In parameter) and there's closure called completions, so we are calling once we done with personalise without any error. Then we have below code for setting custom attribute installation: 

```
func setInstallationConfiguration(_ isEnabled: String){
            if let installationObj = MobileMessaging.getInstallation(){
                    installationObj.isPushRegistrationEnabled = isEnabled
                    installationObj.customAttributes = ["service-notification" : isEnabled, "transaction-notifications" : isEnabled] 
                    MobileMessaging.saveInstallation(installationObj)
                    { (error) in
                        if error != nil {
                               debugPrint(error.de bugDescription)
                        }else {
                               if MobileMessaging.getInstallation()?.customAttributes == nil {
                                      MobileMessaging.fetchInstallation { (installtion, error) in }
                               }
                         }
                    }  
            }
}
``` 
Here we are done with steps to enable push notification on the infobip. 

**2. Expected result: ** 
There should be reflected externalUserId for every-time on the infobip portal when we try to do the above mentioned step.

**3. Actual result: ** 
Using above mentioned code, ExternalUserId is getting updated sometimes but sometime it is not reflecting in infobip portal and we are not getting an error if it gets failed to updated. 

Links actual results: [ScreenShot1](https://prntscr.com/nvc4hj)

That's occurred in both the platform Android and iOS and our both the platform following this things so please provide us solution or any other way to set externalUserId.

Let us know still you need anything from our end.

Thanks

**Comment by kas-kad** [comment]
Can you repeat the issue on iOS, with SDK logs enabled: ```MobileMessaging.logger = MMDefaultLogger()```

**Comment by akshardarji** [comment]
I have sent mail. 

Got failed with screenshot attachment, so providing you here [screenshot](https://prntscr.com/nveih4)

Please check and let us know if you have any concerns. 

Thanks.

**Comment by akshardarji** [comment]
@kas-kad Thanks for your response.

As per your suggestion, we have tried with `MMNotificationRegistrationUpdated` but it's triggered when registration updated successfully. It's a different thing then our requirement. Our requirement is to get a callback on permission dialog of **allow/don't allow** action so this `MMNotificationCenterAuthRequestFinished` help us to achieve the same. 

Please look into following points and revert me on the same: 

1 ) In Other SDK events, we have tried more with `MMNotificationPersonalized` and `MMNotificationDepersonalized` which is ultimately doing the same as `MobileMessaging.personalize` completion from SDK method so It does not help in our case.
2 ) As you said there's a race condition between registration and saving externalUserId, It means do we need to wait till registration update API completed?
3 ) If we need to wait till registration completion, We do not restrict user for till that time. In that case, we need to find another alternative solution.
4 ) If personalize call not able to save externalUserId as registration process ongoing or not valid registration information available, so at that time you should give us completion with the proper error. In that case currently giving us `<error = nil>` (means it's successfully executed)
5 ) Sometimes when we failed with saving externalUserId, It'll never be saved on the server. We have tried after restarting the application as well.

Thanks.

**Comment by kas-kad** [comment]
@akshardarji you can't use `MMNotificationCenterAuthRequestFinished` as a starting point for personalization, this event doesn't guarantee a valid registration, thus communication with personalize API may be impossible. I don't understand why `MMNotificationRegistrationUpdated` is not suitable for you because this event is a logical result of the `MMNotificationCenterAuthRequestFinished` and the following successful registration.

> 2 ) As you said there's a race condition between registration and saving externalUserId, It means do we need to wait till registration update API completed?

correct

> 3 ) If we need to wait till registration completion, We do not restrict user for till that time. In that case, we need to find another alternative solution.

please clarify what restrictions you are talking about

> 4 ) If personalize call not able to save externalUserId as registration process ongoing or not valid registration information available, so at that time you should give us completion with the proper error. In that case currently giving us <error = nil> (means it's successfully executed)

I agree, we should fix this.

> 5 ) Sometimes when we failed with saving externalUserId, It'll never be saved on the server. We have tried after restarting the application as well.

Sorry, I might've confused you. The SDK will retry `saveUser` and `saveInstance` calls eventually, but `personalize` will not be retried if failed.

**Comment by kas-kad** [comment]
@akshardarji 
> 4 ) If personalize call not able to save externalUserId as registration process ongoing or not valid registration information available, so at that time you should give us completion with the proper error. In that case currently giving us <error = nil> (means it's successfully executed)

I've just double-checked it, we actually do return an error if personalize call failed due to missing registration and your logs confirm that:

```2019-05-30 17:12:44:066 [MobileMessaging] ⚠️ [PersonalizeOperation] there is no registration. Finishing...
2019-05-30 17:12:44:067 [MobileMessaging] 🛠 [PersonalizeOperation] finished with errors: [Error Domain=com.mobile-messaging Code=1 "The application instance is not registered on the server yet. The registration will be perfomed eventually. Subscribe to the notification `MMRegistrationUpdated` to be notified as the registration succeeded." UserInfo={NSLocalizedDescription=The application instance is not registered on the server yet. The registration will be perfomed eventually. Subscribe to the notification `MMRegistrationUpdated` to be notified as the registration succeeded.}]```

**Comment by kas-kad** [comment]
@akshardarji regarding the faulty error propagation for `personalize` API (pt. 4), it has been fixed and released now in ver. 5.2.3.

**Comment by akshardarji** [comment]
@kas-kad Thanks for your new release.

We have upgraded release Ver. 5.2.3 and now we are in testing phase so we'll get back to you for the same. 

Meanwhile we found another thing while setting installation `custom attribute`. We have following error in console: 

>(Error Domain=com.mobile-messaging.backend Code=0 \"Registration does not exist\" UserInfo={NSLocalizedDescription=Registration does not exist, messageId=NO_REGISTRATION, text=Registration does not exist})"

I have tried many times `MobileMessaging.saveInstallation` but every-time give me this error, please provide any solutions for this.

**Comment by kas-kad** [comment]
@akshardarji Please create a separate issue for the question and provide push registration id

**Comment by akshardarji** [comment]
@kas-kad Greeting of the day...

Here is the update for your fix: 

> We have upgraded release Ver. 5.2.3 and now we are in testing phase so we'll get back to you for the same.

I willing to share good news and thanks for great support to fixed this issue. 

We have handled race condition case by prompting user to `Try Again` whenever we got error while presonalise means your last release `release/5.2.3` worked for us. 

Thanks :)
