### ISSUE TITLE
Contact information removed from InfoBip portal

### ISSUE THREAD

**Issue by devalchauhan** [infobip/mobile-messaging-sdk-ios#13]
Hello Team,

We are experiencing weird behavior with InfoBip portal. Please find the scenario detail as per below.

* We have registered one user with InfoBip portal.
* We were able to send push notification through InfoBip portal to the registered user.
* Somehow, contact information for the registered user removed from InfoBip portal, and the user is not able to receive a push notification, I am wondering how contact information removed from the portal.

I have attached a few screenshots for the same, Could you please help me to get it resolved.

**Screenshot for the user with contact information:**
* Saturday we had data for the user, please check below screenshots for the same.
1 ) 
![contact_information_with_data](https://user-images.githubusercontent.com/1390592/58783183-f54a0600-85fd-11e9-9604-d200ae7066ce.jpg)
2 ) 
![contact_information_details](https://user-images.githubusercontent.com/1390592/58783209-00049b00-85fe-11e9-98d7-3b1a9a9cfa56.jpg)

**Screenshot for the user without contact information:**
* Today we are not able to see the contact information for the same user, which existed on the portal.
1 ) 
![contact_information_blank](https://user-images.githubusercontent.com/1390592/58784573-617a3900-8601-11e9-9e98-de7c8e8a69e6.jpg)

Thanks,
Deval

**Comment by kas-kad** [comment]
Hello, I will check the data and get back to you.

**Comment by kas-kad** [comment]
@devalchauhan did you re-install the application? Usually it triggers the destination to be expired.

**Comment by kavathiyamahesh** [comment]
Hello @kas-kad 
So the client was checking this issue in Android and IOS both using the same userId, No, we have not re-install the application.

**Comment by kas-kad** [comment]
From our logs I see that the iPhone 7 Plus called our `DELETE /mobile/1/appinstance/<push registration id>` API. This happens only on iOS application reinstall. Can you provide SDK logs from this device for further research? We persist logs on disk so they can be retrieved and sent via email simply using `MobileMessaging.logger?.sendLogs(...)` API.

**Comment by devalchauhan** [comment]
Hello @kas-kad,

Thank you very much for your reply, There might be a chance the client has re-install the application.
It means if we re-install the application on the same device and try to register for push notification, it will remove older contact information, right? In this case, new contact information should register. 

Regarding crash log, will gather it from the client as well try to reproduce from our side and provide you sooner.  

Thanks,
Deval

**Comment by kas-kad** [comment]
@devalchauhan Hi, contact information will not be removed on re-installation, we remove only push destination that is no longer valid. After re-installation, it's possible to personalize the new installation with an existing person data (see [our personalization docs](https://github.com/infobip/mobile-messaging-sdk-ios/wiki/Users-and-installations#user)).

**Comment by devalchauhan** [comment]
Hello @kas-kad,

We are using the below method to register a user for push notification.

```
MobileMessaging.personalize(forceDepersonalize: true, userIdentity: userIdentity!, userAttributes: MobileMessaging.getUser(), completion: { (error) in
            guard error == nil else {
                print(error?.description ?? "")
                return
            }
        })
```
It means we are not adding or removing any contact information intentionally to or from InfoBip portal. The method itself add or update the user's contact information to the InfoBip portal for every installation and re-installation. 

I am wondering how contact information is removed for the user when we are not calling any method that removes the contact information from the portal.


Unfortunately, we are not able to reproduce this from our side at the moment. But we had one occurrence,  and it will become a blocker for the user to get a push notification.  

@kas-kad please guide us what you need from our side to investigate this further and any correction in the code if it is required.

**Comment by kas-kad** [comment]
In order to help you with the issue, I need to know what is the issue, i.e. to be able to reproduce it.

**Comment by kas-kad** [comment]
Please note that depersonalization indeed means removal of all user data. Please also note that on app re-install there is no depersonalization happening, but It's a separate procedure called registration expiration.

**Comment by kas-kad** [comment]
I don't see any issue with your code though.

**Comment by devalchauhan** [comment]
@kas-kad Anyways we had only single occurrence for this issue, and not able to reproduce it at the moment. 
We will ask the end user to perform testing again and if we encounter again, will ask for your further assistance. Allow me some time to discuss with the end user and will get back to you.

**Comment by devalchauhan** [comment]
@kas-kad We didn't find more occurrences for this issue, hence closing the ticket.

**Comment by devalchauhan** [comment]
Hello @kas-kad,

Today we found one more occurrence of this issue, I cannot find contact information for ExternalPersonalID "4693097e3c1c8155127d44eb41c5fb342e19feeaa565937b4b5ecd78e2345fbf".

Please find attached screenshots.
<img width="1792" alt="Screenshot 2019-06-17 at 2 24 27 PM" src="https://user-images.githubusercontent.com/1390592/59591780-47b21900-910c-11e9-9839-856750db6be5.png">
<img width="1792" alt="Screenshot 2019-06-17 at 2 28 27 PM" src="https://user-images.githubusercontent.com/1390592/59591782-47b21900-910c-11e9-9977-32484c89a80d.png">

**Comment by kas-kad** [comment]
Hello, I will check the data and get back to you.

**Comment by kas-kad** [comment]
The missing destination was removed due to APNS rejection reason: "Unregistered". Most likely the app uninstall happened between June 17th 2019, 07:34:40.873 and June 17th 2019, 07:40:14.181.

**Comment by devalchauhan** [comment]
@kas-kad it is hard to identify we unstalled app between given time or not, sorry for the delay in reply. We don't have any more occurrences for this issue, closing it for now.
