### ISSUE TITLE
Intermittent issue with push notification delivery

### ISSUE THREAD

**Issue by devalchauhan** [infobip/mobile-messaging-sdk-ios#14]
Hello Team,

We are facing an intermittent issue with sending push notification through InfoBip portal to the Android and iOS devices.

* We have valid recipients registered on InfoBip portal from Android and iOS devices.
* We are trying to send push notification to the registered user through InfoBip portal using Segmentation as well as to the All recipients.
* We observed that sometimes recipients receive a push notification and sometimes they didn’t receive for the same segment and configuration.

**NOTE:** On last Saturday (1st June 2019), this issue was frequent.

I have attached a few screenshots for the same, Could you please help me to get it resolved.

1 )
![Infobip_SDK](https://user-images.githubusercontent.com/1390592/58786389-0fd3ad80-8605-11e9-95a5-d482cfc60b84.png)
 
2 )
![Infobip_SDK_Detail](https://user-images.githubusercontent.com/1390592/58786394-13673480-8605-11e9-82ee-fb26866e713d.png)

Thanks,
Deval

**Comment by kas-kad** [comment]
@devalchauhan There was an issue on the back-end side caused by faulty deployment, however, this issue has been successfully resolved yesterday and should no longer be observed.

**Comment by devalchauhan** [comment]
@kas-kad Thank you for your reply, the end user is verifying. Will update you once we receive feedback from them.

**Comment by devalchauhan** [comment]
@kas-kad We didn't find more occurrences for this issue, hence closing the ticket.
