### ISSUE TITLE
support SPM

### ISSUE THREAD

**Issue by Hokila** [infobip/mobile-messaging-sdk-ios#17]
# Please fill out the following form to help us to resolve you issue faster.

* MobileMessaging SDK version: 6.0
* Xcode version: 11.4
* Your application language: swift 5
* Cocoapods version: none

Is it possible support SPM install. add a Package.swift

<img width="715" alt="截圖 2020-04-01 上午11 27 59" src="https://user-images.githubusercontent.com/1647434/78096334-ded22e00-740b-11ea-9fa0-9537f861a6a5.png">

**Comment by kas-kad** [comment]
Hello, we don't support SPM by now since we had no requests for it so far. However, you are welcome to contribute.
