### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by DmytroYashchenko** [infobip/mobile-messaging-sdk-ios#22]
* MobileMessaging SDK version: 6.2.4
* Xcode version: 11.6
* Your application language: Swift
* Cocoapods version: 1.9.2

Got "Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value" in ApnsRegistrationManager.updateDeviceToken method after firing of application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data).

**Comment by kas-kad** [comment]
Hello, thank you for the report. I'll keep you informed of the fix.

**Comment by DmytroYashchenko** [comment]
FIXED. It was my mistake. Sorry.
