### ISSUE TITLE
6.2.6 version showing same problem fixed on 8.3.3 version

### ISSUE THREAD

**Issue by mvp-sales** [infobip/mobile-messaging-sdk-ios#29]
I found some crashes are happening in the `UserNotificationCenterDelegate` class, at the line 63, saying that "Call must be made on main thread". I suppose it's the same problem that was fixed in the 8.3.3 version.

* MobileMessaging SDK version: 6.2.6
* Xcode version: 12.0
* Your application language: Swift 5.0
* Cocoapods version: 1.9.3

**Comment by kas-kad** [comment]
@mvp-sales sorry to have kept you waiting so long, we've lost your report. Yes, the bugfix was implemented only for version 8. We will release it for version 6 shortly. Will keep you updated.

**Comment by kas-kad** [comment]
@mvp-sales version 6.2.7 has been released containing the bugfix

**Comment by mvp-sales** [comment]
@kas-kad Thanks, I've checked and I found no crashes happening with the 6.2.7 version
