### ISSUE TITLE
No known class method for selector 'didReceiveLocalNotification:'

### ISSUE THREAD

**Issue by imuhammadjabbar** [infobip/mobile-messaging-sdk-ios#3]
Facing this issue when using the following method:
// in order the MobileMessaging SDK to be able to handle incoming local notifications internally:
-(void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {
    [MobileMessaging didReceiveLocalNotification:notification]; // Not Working
}

Attached is the screenshot.

Thanks

![screen shot 2016-11-24 at 5 53 56 pm](https://cloud.githubusercontent.com/assets/12771786/20599333/619ef6f4-b26f-11e6-97fe-8adc10d81503.png)

**Comment by kas-kad** [comment]
Hello, @imuhammadjabbar, which version of library do you use?
