### ISSUE TITLE
In-app notification alert

### ISSUE THREAD

**Issue by zidarj** [infobip/mobile-messaging-sdk-ios#30]
Present Alert function doesnt work because my rootVc is UINavigationController
![Screenshot 2021-01-11 at 09 56 01](https://user-images.githubusercontent.com/45390141/104162233-7ed5d280-53f4-11eb-8059-c1ae7a8b2c77.png)
simple fix for this bug is UIApplication extension

    @objc class func topViewController(_ base: UIViewController? = UIApplication.shared.keyWindow?.rootViewController) -> UIViewController? {
        
        if let nav = base as? UINavigationController {
            return topViewController(nav.visibleViewController)
        }
        
        if let tab = base as? UITabBarController {
            let moreNavigationController = tab.moreNavigationController
            
            if let top = moreNavigationController.topViewController , top.view.window != nil {
                return topViewController(top)
            } else if let selected = tab.selectedViewController {
                return topViewController(selected)
            }
        }
        
        if let presented = base?.presentedViewController {
            return topViewController(presented)
        }
        
        return base
    }

* MobileMessaging SDK version: 8.3.9
* Xcode version: 12.3
* Your application language: Swift 5
* Cocoapods version: 0.0.7.7

**Comment by kas-kad** [comment]
Hello, thanks for the report and solution. We can fix it in sevaral ways asctually. Would it be better to introuduce a special delegate API for you to provide the presenting VC in customized and dynamic way? The same way as we have it for in-app webviews:

```
/// Called when a web view is about to be shown. It's required to provide a view controller that will present the web view.
/// - parameter message: `MTMessage` object, that has a special URL (see `webViewUrl` property) to be opened in the web view.
/// - returns: Parent view controller that would be used to present the web view. If you return `nil`, the web view would not be shown up.
@objc optional func inAppWebViewPresentingViewController(for message: MTMessage) -> UIViewController?
```

**Comment by zidarj** [comment]
Yes that is better solution

**Comment by kas-kad** [comment]
Ok, we'll implement it within a few days and let you know.

**Comment by zidarj** [comment]
Thank You :D

**Comment by riskpp** [comment]
Hello @zidarj, we've released bunch of fixes today - version [8.4.0](https://github.com/infobip/mobile-messaging-sdk-ios/releases/tag/).

We fixed default topmost view controller for presenting in-app notification alert and also added [delegate API to provide custom presenting view controller](https://github.com/infobip/mobile-messaging-sdk-ios/wiki/In-app-notifications#setup-custom-view-controller-for-presenting-in-app)

Hope it will suit you!

BR,
Olga

**Comment by riskpp** [comment]
Hello @zidarj, I'm closing the issue, because it was fixed and we didn't receive other questions.
BR,
Olga

**Comment by zidarj** [comment]
Ok
Thanks

čet, 28. sij 2021. 13:38 Olga Koroleva <notifications@github.com> je
napisao:
