### ISSUE TITLE
Don't find MobileMessaging.notificationTapHandler

### ISSUE THREAD

**Issue by 1MaXimus** [infobip/mobile-messaging-sdk-ios#33]
How I must catch taps on notification? Tell me, please! 

* MobileMessaging SDK version: 9.1.10
* Xcode version: 12.5
* Your application language: Swift 4.2
* Cocoapods version: 1.10.1
Можно по-русски ответить.

**Comment by riskpp** [comment]
Hello @1MaXimus,
You can find instruction by the link - https://github.com/infobip/mobile-messaging-sdk-ios/wiki/How-to-handle-a-message-when-user-opens-the-app-by-tapping-on-a-notification-alert%3F

**Comment by 1MaXimus** [comment]
Спасибо, Ольга! 
Поправите же в Wiki по поводу MobileMessaging.notificationTapHandler.
