### ISSUE TITLE
MobileMessaging not working with application extension

### ISSUE THREAD

**Issue by svshkv** [infobip/mobile-messaging-sdk-ios#34]
Hello!

I'm trying to use MobileMessaging with my application extension and for UIApplication.shared I get "'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.".

<img width="848" alt="Снимок экрана 2021-10-20 в 12 38 20" src="https://user-images.githubusercontent.com/22290695/138070055-42cb2f5c-0a60-4c14-aff7-dfa4f155c3b7.png">

* MobileMessaging SDK version: 9.2.7
* Xcode version: 13.0 
* Your application language: Swift 5
* Cocoapods version: 1.10.1

**Comment by riskpp** [comment]
Hello @svshkv, 
You can check how to integrate MobileMessaging SDK into NotificationServiceExtension in our Example application:
1. [NotificationExtension.swift](https://github.com/infobip/mobile-messaging-sdk-ios/blob/master/Example/NotificationServiceExtension/NotificationService.swift)
2. Don't forget to add appGroups, first [setup app group for an app id](https://github.com/infobip/mobile-messaging-sdk-ios/wiki/Notification-Service-Extension-for-Rich-Notifications-and-better-delivery-reporting-on-iOS-10#setting-up-app-group-id-for-an-app-id), then set it in xCode (Signing and Capabilities) for you main application target and NotificationExtension target,  add group id to the Info.plist file as in [Example application info.plist](https://github.com/infobip/mobile-messaging-sdk-ios/blob/master/Example/MobileMessagingExample/Info.plist#L58)

We have tool to automatically add Notification Extension with integrated into it MobileMessaging SDK, could be also useful to check this doc - https://github.com/infobip/mobile-messaging-sdk-ios/wiki/Notification-Service-Extension-for-Rich-Notifications-and-better-delivery-reporting-on-iOS-10

BR, Olga

**Comment by riskpp** [comment]
As I said warnings can be ignored for now, we created a task to change it in future.

**Comment by LFMAKER** [comment]
@riskpp I'm having the same problem with react native 0.67 and latest version of mobile-messaging-react-native-plugin
