### ISSUE TITLE
Got Duplicate Notification

### ISSUE THREAD

**Issue by tomdwipo** [infobip/mobile-messaging-sdk-ios#37]
# Got Duplicate Notification

* MobileMessaging SDK version: 9.2.11
* Xcode version: 13.1
* Your application language: swift
* Cocoapods version: 1.11.2
* iOS 15

Got duplicate notification when chat get in

**Comment by tjuric** [comment]
Hi @tomdwipo,
Have you maybe reached us out over official Infobip's support support@infobip.com? Is this issue still persistent or you have figured out the source of it?

BR,
Tereza

**Comment by tomdwipo** [comment]
Hi @tjuric 

problem solved.

Thanks!
