### ISSUE TITLE
Application crush when trying to set device as primary

### ISSUE THREAD

**Issue by beltik** [infobip/mobile-messaging-sdk-ios#38]
Hello,

* MobileMessaging SDK version: 9.2.12
* Xcode version: 13.1
* Your application language: Swift 5
* Cocoapods version: 1.11

In attempt to set device as a primary with following code, i got application crush (not all of the time, but mostly. Application run in Debug mode).

 if let installation = MobileMessaging.getInstallation() {
        MobileMessaging.setInstallation(withPushRegistrationId: installation.pushRegistrationId ?? "",
                                        asPrimary: true) { installation, error in
          if let error = error {
            completionFailure()
          }
          completionSuccess()
        }
    }

<img width="1759" alt="Screenshot 2022-02-17 at 18 51 48" src="https://user-images.githubusercontent.com/6133772/154518947-967f8a42-74ef-4304-872a-44b70105df29.png">

Have tried to wrap it in global queue, but have the same results.

**Comment by kas-kad** [comment]
@beltik Hello
thank you for the report. We'll take a look shortly.

**Comment by kas-kad** [comment]
@beltik
we are preparing a fix for this case, going to release it tomorrow. Until then, you can remove the line 90, it would work fine.

**Comment by kas-kad** [comment]
@beltik 
A new version of MobileMessaging was released with version 9.2.14
