### ISSUE TITLE
Remove CocoaLumberjack Dependency from Podfile

### ISSUE THREAD

**Issue by stupergenius** [infobip/mobile-messaging-sdk-ios#4]
**Template**

* MobileMessaging SDK version: 2.1.3
* Xcode version: N/A
* Your application language: Objective-C
* Cocoapods version: N/A
* How do you integrate MobileMessaging SDK with your code?: Cocoapods

**Issue**

We would prefer that the CocoaLumberjack pod not be included as a dependency in the podspec. This forces all consumers of the messaging SDK to also have a (perhaps) needless dependency on CocoaLumberjack.

As far as I can tell, it is only used in this repo for the example project. As such, perhaps the example project itself could depend on the MobileMessaging pod as well as the CocoaLumberjack pod. This means the main MobileMessaging pod would be free from dependency on CocoaLumberjack, while the example would function as it currently does.

**Comment by kas-kad** [comment]
Hello, @stupergenius 
CocoaLumberjack is used for internal MobileMessaging SDK logging. It is disabled by default for release builds. Unfortunately you can't get rid of this dependency at this moment, but we'll provide this option in future.

**Comment by kas-kad** [comment]
@stupergenius 
We've released 2.2.0. Now you can install the SDK without CocoaLumberjack. Podfile should be like this:
```
pod 'MobileMessaging/Core'
```

**Comment by stupergenius** [comment]
Nice! Thanks.
