### ISSUE TITLE
Use of '@import' when C++ modules are disabled, consider using -fmodules and -fcxx-modules

### ISSUE THREAD

**Issue by lucasoliveiraw00** [infobip/mobile-messaging-sdk-ios#40]
Hello, I have an error when performing `@import MobileMessaging;` import, could you help me with this problem?

AppDelegate.mm: `Use of '@import' when C++ modules are disabled, consider using -fmodules and -fcxx-modules`

When adding the indicated flags, errors occur in other libraries when compiling.

* MobileMessaging SDK version: 9.2.16
* Xcode version: 14.0.1
* Your application language: Objective-C++
* Cocoapods version: 1.11.3

_Originally posted by @lucasoliveiraw00 in https://github.com/infobip/mobile-messaging-sdk-ios/issues/6#issuecomment-1273606476_

**Comment by riskpp** [comment]
Hi @lucasoliveiraw00 which errors occur on other libraries with `-fcxx-modules` option?
I'm not sure that we could help here much, the other solution is to try to make your own wrapper for the MobileMessaging module and use interfaces from it's header file, but it looks not very easy.

**Comment by riskpp** [comment]
About the wrapper, this is just a simple example:

MobileMessagingCustomWrapper.h
```objective-c
#import <Foundation/Foundation.h>

@interface MobileMessagingCustomWrapper : NSObject

+ (void)startMobileMessagingWithApplicationCode:(NSString * _Nonnull)code;

@end
```
MobileMessagingCustomWrapper.m
```objective-c
#import "MobileMessagingCustomWrapper.h"

@import MobileMessaging;

@implementation MobileMessagingCustomWrapper

+ (void)startMobileMessagingWithApplicationCode:(NSString * _Nonnull)code {
    MMUserNotificationType *userNotificationType = [[MMUserNotificationType alloc] initWithOptions:@[MMUserNotificationType.alert, MMUserNotificationType.sound]];
    [MobileMessaging withApplicationCode: code notificationType: userNotificationType];
}

@end
```

**Comment by lucasoliveiraw00** [comment]
> Hi @lucasoliveiraw00 which errors occur on other libraries with `-fcxx-modules` option? I'm not sure that we could help here much, the other solution is to try to make your own wrapper for the MobileMessaging module and use interfaces from it's header file, but it looks not very easy.

The following errors occur:
![Captura de Tela 2022-10-11 às 11 24 13](https://user-images.githubusercontent.com/42048768/195120117-3d124e1d-d1a6-448c-b9da-b58b25094c16.png)

@riskpp could you tell me what option it would be to add the '-fcxx-modules' flag?

**Comment by riskpp** [comment]
This is the screenshot which I did from the [Example app](https://github.com/infobip/mobile-messaging-react-native-plugin/tree/master/Example)
<img width="1212" alt="Screenshot 2022-10-11 at 18 08 35" src="https://user-images.githubusercontent.com/8104718/195129378-7aee365f-1635-432e-9a4c-19d7ac56f20c.png">

**Comment by lucasoliveiraw00** [comment]
> About the wrapper, this is just a simple example:
> 
> MobileMessagingCustomWrapper.h
> 
> ```objc
> #import <Foundation/Foundation.h>
> 
> @interface MobileMessagingCustomWrapper : NSObject
> 
> + (void)startMobileMessagingWithApplicationCode:(NSString * _Nonnull)code;
> 
> @end
> ```
> 
> MobileMessagingCustomWrapper.m
> 
> ```objc
> #import "MobileMessagingCustomWrapper.h"
> 
> @import MobileMessaging;
> 
> @implementation MobileMessagingCustomWrapper
> 
> + (void)startMobileMessagingWithApplicationCode:(NSString * _Nonnull)code {
>     MMUserNotificationType *userNotificationType = [[MMUserNotificationType alloc] initWithOptions:@[MMUserNotificationType.alert, MMUserNotificationType.sound]];
>     [MobileMessaging withApplicationCode: code notificationType: userNotificationType];
> }
> 
> @end
> ```
> 
> AppDelegate.mm
> 
> ```objc
> #import "MobileMessagingCustomWrapper.h"
> 
> @implementation AppDelegate
> 
> - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
>     
>     [MobileMessagingCustomWrapper startMobileMessagingWithApplicationCode:@"Your app code"];
> 
>   return YES;
> }
> @end
> ```

@riskpp, thank you very much, this solution worked!

**Comment by riskpp** [comment]
You are welcome, I'll close the issue then.
