### ISSUE TITLE
The app crashes on iOS 16 when the user turn back to app after on the system notification.

### ISSUE THREAD

**Issue by Chanick-Park** [infobip/mobile-messaging-sdk-ios#44]
Notice: for security reasons, don't ever disclose your Application Code and other sensitive information, Github is a public resource, anyone can see comments that you post here.

* MobileMessaging SDK version: 10.0.0
* Xcode version: 14.2
* Your application language: swift 5, Obj-c
* Cocoapods version: 1.12.1

### The app crashes on iOS 16.5 when user turn off push notification and turn on..,back and forth. Below is call stack info screenshot.

The `remoteApiProvider` is set to nil on the `doStop()` It always happed on the prev version as well.

![image](https://github.com/infobip/mobile-messaging-sdk-ios/assets/129877959/c841bba5-3ba6-4d3e-bec1-43eb9f13d087)

**Comment by riskpp** [comment]
Hello @Chanick-Park could you please add more description to this scenario, have you implemented something special "when user turn off push notification and turn on" may be? And what do you actually mean by "turn off push notification and turn on", by making that on the device level I didn't manage to reproduce it in [Example app](https://github.com/infobip/mobile-messaging-sdk-ios/tree/master/Example).

**Comment by Chanick-Park** [comment]
@riskpp In our app, the mobile messaging service starts or ends whenever the user turns push notification off or on.
app call the `updateInstallationForRemoteNotifications (to: true/false)` when user turned on or off. 

When push notification is turned off or on in the app, the screen is switched to the system setting screen to synchronize with the system. If user turn it off and then turn it on again, the instance's `notificationType` changes and update `requiresRestart = true `. In this case, `doStop()` is called and the `remoteApiProvider` becomes nil, so a nil reference in `validateVersion()` causes a crash.
 
``` swift
private func registerForPushNotificationsIfNecessary() {
        DispatchQueue.main.async { [weak self] in
            guard let weakSelf = self else { return }
            if !weakSelf.isRegisteredForRemoteNotifications, SharedProperties.sharedInstance.appNotificationsEnabled {
                MobileMessaging.logger?.logLevel = .Warning
                MobileMessaging.withApplicationCode(BuildConfiguration.configValue(for: .infoBip),
                                                    notificationType: MMUserNotificationType(options: [.alert, .sound]))?.start()
                MobileMessaging.messageHandlingDelegate = weakSelf
                weakSelf.updateInstallationForRemoteNotifications(to: true)
            } 
        }
    }

private func updateInstallationForRemoteNotifications(to enable: Bool) {
        guard let installation = currentInstallation else {
            return
        }
        installation.isPushRegistrationEnabled = enable
        isRegisteredForRemoteNotifications = enable

        if enable {
            updatePushNotificationsProfile(for: installation)
        }

        MobileMessaging.saveInstallation(installation) { (error) in
            // save error
    }
```

**Comment by riskpp** [comment]
@Chanick-Park you could try to not stop MobileMessaging SDK or not change notificationType in case if user switched off push notifications, setting of `isPushRegistrationEnabled = false` is enough to switch off all push notifications from MobileMessaging.

However `remoteApiProvider becomes nil` issue shouldn't appear if you restarted the SDK with different parameters, could you please try the following:
1 - Wait when call of mobile Messaging start finishes (completion) before starting next one 
2 - Subscribe to [MMNotificationRegistrationUpdated event](https://github.com/infobip/mobile-messaging-sdk-ios/wiki/Library-events) and wait for its invocation -> that's the time when library gets connected to Infobip's backend (push registration ID is generated), after that you can call saveInstallation method

We might have a problem in case if `stop` method is not called between the two SDK starts with different parameters, I'll create issue about that, however you may try to call [`stop`](https://github.com/infobip/mobile-messaging-sdk-ios/blob/master/Classes/Core/MobileMessaging.swift#L130), if you still want to stop the SDK, this is the example code of how I tested the restart of SDK, it works ok:
```
        let group = DispatchGroup()
        let mainQ = DispatchQueue.main
        
        group.enter()
        
        mainQ.async {
            MobileMessaging
                .withApplicationCode(
                    "App Code",
                    notificationType: MMUserNotificationType(options: []))?
                .withInteractiveNotificationCategories(self.customCategories)
                .start({
                    group.leave()
                })
        }
        
        group.notify(queue: DispatchQueue.main) {
            mainQ.async {
                MobileMessaging.stop(false) {
                    MobileMessaging
                        .withApplicationCode(
                            "App Code",
                            notificationType: MMUserNotificationType(options: [.alert, .sound]))?
                        .withInteractiveNotificationCategories(self.customCategories)
                        .start()
                }
            }
        }

**Comment by Chanick-Park** [comment]
@riskpp Thank you for your quick response. I will try to double check this issue with your suggestion.
And I think, I found an issue in `MobileMessaging` class init function about the compare `userNotificationType`.
It would be change to `sharedInstance.userNotificationType.rawValue != notificationType.rawValue` for checking their value.

````swift
internal init?(appCode: String, notificationType: MMUserNotificationType, backendBaseURL: String, internalStorage: MMCoreDataStorage? = nil) {
...........
if let sharedInstance = MobileMessaging.sharedInstance, sharedInstance.applicationCode != appCode || sharedInstance.userNotificationType != notificationType || sharedInstance.remoteAPIBaseURL != backendBaseURL {
            requiresRestart = true
        }
...........
}
````

**Comment by riskpp** [comment]
closing the issue, because was fixed
