### ISSUE TITLE
App Crash issue [Release build]

### ISSUE THREAD

**Issue by Chanick-Park** [infobip/mobile-messaging-sdk-ios#45]
* MobileMessaging SDK version: 10.19.1
* Xcode version: 14.2
* Your application language: Swift 5
* Cocoapods version: 1.12.1

The app crashes on the `Release Build` since Infobip release `10.15.4`. It seems that unnecessary options are set in the Swift compiler options. 
Please let me know why you set this options if this options is required. @riskpp 

![image](https://github.com/infobip/mobile-messaging-sdk-ios/assets/129877959/8d2c296d-df53-4c8b-86ca-a0b4da779573)

**Comment by fortesdev** [comment]
Hi @Chanick-Park, those flags are defined in the Swift compiler options if you have the following line in your podfile:
_**pod 'MobileMessaging/WebRTCUI'**_
(as seen in the MobileMessaging SDK podspec: https://github.com/infobip/mobile-messaging-sdk-ios/blob/master/MobileMessaging.podspec)

Could you please help us understanding the issue by answering what's your case?
- You added the WebRTCUI subpod, but don't want it (in which case, you can just remove the line, and do "pod deintegrate" and "pod install")
- You want the WebRTCUI subpod but one of the flags ("-D DEBUG" or "-D WEBRTCUI_ENABLED") is crashing your build.

Definitely I can say DEBUG flag should not be added to all your build configurations, and I apologise for that (a fix will come shortly). But  WEBRTCUI_ENABLED flag must be there if you want the WebRTCUI feature. 
Please confirm if that's the case.

**Comment by Chanick-Park** [comment]
Hi @fortesdev Thank you for your quick response. 
- Team have decided to update new version 10.19.1 because potential crash issues (previously, team used the version 10.0.0) https://github.com/infobip/mobile-messaging-sdk-ios/issues/42 
- But the flags ("-D DEBUG") is crashing on the release build

The new version 10.19.2 works fine now! Thank you very much.
