### ISSUE TITLE
Unable to build on iOS 17

### ISSUE THREAD

**Issue by SaurabhPrajapati** [infobip/mobile-messaging-sdk-ios#49]
* MobileMessaging SDK version: 10.23.0
* Xcode version: 15.0 beta 6 (15A5219j)
* Your application language: Swift
* Cocoapods version: 1.11.3

With Xcode 15 beta, Not able to build app as issue with `completionBlock` property on `Operation` class. Please check attached screenshot.

<img width="978" alt="Screenshot 2023-08-24 at 11 08 22 AM" src="https://github.com/infobip/mobile-messaging-sdk-ios/assets/9278182/e5672554-a019-48b6-9ed1-7e6fd8601d95">

**Comment by riskpp** [comment]
Hello @SaurabhPrajapati, thank you for noticing, it was fixed in the https://github.com/infobip/mobile-messaging-sdk-ios/releases/tag/10.23.1 version.
