### ISSUE TITLE
Compile error in version 2.5.5

### ISSUE THREAD

**Issue by int-el** [infobip/mobile-messaging-sdk-ios#5]
MMUserAgent.swift:220:43: '[String : AnyHashable]?' is not convertible to '[Key : Value]'

![screen shot 2017-05-03 at 11 17 34](https://cloud.githubusercontent.com/assets/28335871/25649832/21b2072e-2ff2-11e7-88ea-827a4b07584e.png)

* MobileMessaging SDK version: 2.5.5
* Xcode version: 8.2.1
* Your application language: Swift 3.0
* Cocoapods version: 1.2.0
* How do you integrate MobileMessaging SDK with your code?:  App delegate composition

**Comment by riskpp** [comment]
Hi @int-el Thank you for reporting,
to fix this just update to the latest xCode 8.3.2.
