### ISSUE TITLE
10.25.0 not deployed on pod

### ISSUE THREAD

**Issue by EArminjon** [infobip/mobile-messaging-sdk-ios#50]
pod 'MobileMessaging', '10.25.0'
```
[!] CocoaPods could not find compatible versions for pod "MobileMessaging":
  In Podfile:
    MobileMessaging (= 10.25.0)
```

**Comment by riskpp** [comment]
Hello @EArminjon, I also see that error, we'll check what we can do with it.
You could try to use 11.0.0 version, there is one feature added, if you don't use it, it shouldn't affect you https://github.com/infobip/mobile-messaging-sdk-ios/wiki/Migration-guides#migration-guide-from-10x-to-11x

**Comment by riskpp** [comment]
10.25.0 is not deployed on cocoapods, unfortunately we can't do anything with it. But 11.0.0 version might be used.
