### ISSUE TITLE
Problems with Apple's new PrivacyInfo

### ISSUE THREAD

**Issue by fabianPay** [infobip/mobile-messaging-sdk-ios#53]
Hello, when I get the privacy report I have a problem, apparently you have to set the NSPrivacyCollectedDataTypes permission, when will there be a solution to this since you have until May 1 to adapt to these changes

![image](https://github.com/infobip/mobile-messaging-sdk-ios/assets/154635901/42edd9bb-bfca-44b1-b177-1490f6e5f566)

* MobileMessaging SDK version: 12.5.0
* Xcode version: 15.2
* Your application language: Swift 5.9.2
* Cocoapods version: 1.14.3

**Comment by fortesdev** [comment]
Hi @fabianPay, thanks for pointing this out. A fix will be available next week.

**Comment by fortesdev** [comment]
Hi @fabianPay, we have completed our privacy manifest today in the new version 12.5.1. Something important to keep in mind, though: we do mention only the strictly necessary usage of our base SDK. 

There are features, like geofencing, or personalising with user contact information, that are up to the integrator, and as such, they should be mentioned in the parent app manifest. In other words: if your app does some specific data usage [mentioned here](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests), please do add it to your PrivacyInfo.
