### ISSUE TITLE
Use of '@import' when C++ modules are disabled

### ISSUE THREAD

**Issue by torodavit** [infobip/mobile-messaging-sdk-ios#6]
* MobileMessaging SDK version: 2.8.1
* Xcode version: 8.3.3
* Your application language: Objective-C
* Cocoapods version: 1.3.1
* How do you integrate MobileMessaging SDK with your code?: "App delegate composition"?

I have old project on Objective c++.
I have this error message when type '@import', file is c++ file .mm what can i do?

AppDelegate.mm: Use of '@import' when C++ modules are disabled, consider using fmodules and fcxx-modules

**Comment by stanislavin** [comment]
Hi @torodavit, sorry for delayed response.

Can you please try adding `-fcxx-modules` to C++ compiler flags  for Debug/Release and let me know if it fixes your issue.

![Screenshot](https://monosnap.com/file/d94UXfx7q2LGp3850KznputTyPXx3P.png)

**Comment by torodavit** [comment]
Thanks, it's work.

**Comment by UmeshChaudhari6057** [comment]
Thanks

**Comment by lucasoliveiraw00** [comment]
Hi, I have the same problem, do you have any recommendations?
* MobileMessaging SDK version: 9.2.16
* Xcode version: 14.0.1
* Your application language: Objective-C
* Cocoapods version: 1.11.3
