### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by alejandro-isaza-hs** [infobip/mobile-messaging-sdk-ios#7]
We have a lot of dependencies and can't afford to use the `use_frameworks!` setting in our Podfile. CocoaPods currently doesn't support mixing frameworks with static libraries. So this means we can't integrate this library using CocoaPods. I tried Carthage but I get `Dependency "mobile-messaging-sdk-ios" has no shared framework schemes for any of the platforms: iOS`. Can you please share a scheme so that we can use Carthage.

**Comment by kas-kad** [comment]
@alejandro-isaza-hs hello, we'll add support for Carthage in a few days

**Comment by kas-kad** [comment]
@alejandro-isaza-hs the very first attempt to provide you with Carthage support is done, you can integrate MobileMessaging SDK with the following line in your Cartfile:
```
github "infobip/mobile-messaging-sdk-ios" "master"
```

**Comment by alejandro-isaza-hs** [comment]
That was fast! Thanks! A new version tag would be great :)

**Comment by alejandro-isaza-hs** [comment]
I spoke too soon. It fails on the CocoaLumberjack dependency. You can add that to the Cartfile, but I would prefer if you remove that dependency.

**Comment by kas-kad** [comment]
@alejandro-isaza-hs ok, I'll fix that today

**Comment by kas-kad** [comment]
@alejandro-isaza-hs I removed the CocoaLumberjack dependency as you requested for. Please try  `carthage update` again. I'll release the tag as soon as everything is ok with your build. As for the failure you had with CocoaLumberjack dependency, I could not reproduce it. Could please describe the prerequisites  and your actions step-by-step? Thank you.

**Comment by alejandro-isaza-hs** [comment]
Running Carthage and compiling works but when you try to launch the app you get a dylib error saying it could not find CocoaLumberjack. I'll give this a try.

**Comment by alejandro-isaza-hs** [comment]
The latest version works except for this error:
```
MobileMessagingAppDelegateObjc.h:29:64: error: declaration does not declare anything [-Werror,-Wmissing-declarations]
@property (nonatomic, readonly) BOOL geofencingServiceEnabled; __attribute__((unavailable("Please use `MobileMessaging.geofencingService.start(completion:)` or `MobileMessaging.withApplicationCode(:notificationType:).withGeofencing().start(:)` in order to enable and start Geofencing services features.")));
```
I fixed it by deleting that declaration.

**Comment by kas-kad** [comment]
@alejandro-isaza-hs Thanks for the feedback, I'll check it!

**Comment by kas-kad** [comment]
@alejandro-isaza-hs I've fixed the error you mentioned, and added a tag. Cartfile may look as follows now
```
github "infobip/mobile-messaging-sdk-ios" ~> 2.0
```

**Comment by alejandro-isaza-hs** [comment]
Nice, thanks!
