### ISSUE TITLE
didRegisterForRemoteNotificationsWithDeviceToken method not called

### ISSUE THREAD

**Issue by akshardarji** [infobip/mobile-messaging-sdk-ios#9]
# Please fill out the following form to help us to resolve you issue faster.

> [MobileMessaging] ‼️ [Checking versions] An error occurred while trying to validate library version: Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9800, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x1d4240bd0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9800, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9800}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://mobile.infobip.com/mobile/3/version?platformType=APNS, NSErrorFailingURLStringKey=https://mobile.infobip.com/mobile/3/version?platformType=APNS, _kCFStreamErrorDomainKey=3}

While doing following steps got above mentioned error: 
`MobileMessaging.withApplicationCode("APPCODE", notificationType: UserNotificationType(options: [.alert, .sound, .badge]))?.start({ })`

Occurred for following call: 
```
mmContext.remoteApiProvider.fetchRecentLibraryVersion(applicationCode: mmContext.applicationCode, pushRegistrationId: mmContext.currentUser.pushRegistrationId) 
{
         self.handleResult(result: $0)
         completion?()
}

func handleResult(result: LibraryVersionResult) {
		if let response = result.value {
			if shouldShowNewVersionWarning(onlineVersion: response.libraryVersion, localVersion: mobileMessagingVersion) {
				showNewVersionWarning(localVersion: mobileMessagingVersion, response: response)
			} else {
				handleUpToDateCase()
			}
		} else {
			MMLogError("[Checking versions] An error occurred while trying to validate library version: \(result.error.orNil)")
		}
	}
```

error printing the log from : 

> MMLogError("[Checking versions] An error occurred while trying to validate library version: \(result.error.orNil)") 

We are blocked here, could you please help me out.

Thanks. 

* MobileMessaging SDK version: [fork: https://github.com/akshardarji/mobile-messaging-sdk-ios.git]
* Xcode version: [10.1]
* Your application language: [swift-4]
* Cocoapods version: [1.5.3]
* Device version: [iPhone 8 plus (iOS-11.0.2)]

**Comment by kas-kad** [comment]
>We are blocked here, could you please help me out.
Hello, pls clarify what do you mean "blocked"?

**Comment by akshardarji** [comment]
For iOS 11.0.2, We didn't called didRegisterForRemoteNotificationsWithDeviceToken method so due to that we can't able to get any push notifications. Please provide me solutions for the same.

**Comment by kas-kad** [comment]
hello, make sure you read [this article](https://github.com/infobip/mobile-messaging-sdk-ios/wiki/I-don't-receive-push-notifications). Let me know if any questions arise.

**Comment by kas-kad** [comment]
What are the other iOS versions you mentioned?

**Comment by akshardarji** [comment]
> Hello, make sure you've read [this article](https://github.com/infobip/mobile-messaging-sdk-ios/wiki/I-don't-receive-push-notifications). Let me know if any questions arise.

I have ready that and working fine for other iOS version but not worked only on iOS 11.0.2. Yes I have setup with sandbox env. 

> What are the other iOS versions you mentioned?

Working Fine on iOS version : (10.x.x, 11.1.x < 11.4.x  , 12.x)

Not Working on iOS version : (11.0.x)

**Comment by kas-kad** [comment]
Did you try to uninstall-install the application?

**Comment by akshardarji** [comment]
Yeah Obviously. I have tried many time and tried after rebooting device too.

**Comment by akshardarji** [comment]
Yeah Obviously. I have tried many time and tried after rebooting device too.

**Comment by kas-kad** [comment]
This looks weird and for me it is impossible to say what may be wrong. The fastest solution would be to check if Push works against production APNS environment (you need to to issue a production APNS certificate, create a Production Push Application on our Portal, provision the application build with Ad-Hoc Provisioning Profile and use a new Application Code for the app build).

**Comment by kas-kad** [comment]
I made a quick search and found [this topic](https://stackoverflow.com/questions/44796613/silent-pushes-not-delivered-to-the-app-on-ios-11), realted to Push issues on early iOS 11's

**Comment by kas-kad** [comment]
@akshardarji have you found a solution?

**Comment by akshardarji** [comment]
Yeah found it. There had applied proxy so that whenever tried to connect APNS, it's been failed that request and due to that never came to _didRegisterForRemoteNotificationsWithDeviceToken_ method.

Thanks for your instant support. 👍

**Comment by apphardtask** [comment]
@akshardarji : You mentioned "There had applied proxy".. Could you please illustrate more on this...

I am also facing issue where didRegisterForRemoteNotificationsWithDeviceToken is not called in iOS 13 (iOS 12 & lower working fine).

**Comment by fparkar** [comment]
@akshardarji : You mentioned "There had applied proxy".. Could you please illustrate more on this...

I am also facing issue where didRegisterForRemoteNotificationsWithDeviceToken is not called in iOS 13 (iOS 12 & lower working fine).

**Comment by akshardarji** [comment]
@fparkar Yes, It's an iOS issue.

You can find the iOS - release note.

Release iOS-13.3.1 - Resolves an issue where push notifications could fail to be delivered over Wi-Fi

https://support.apple.com/en-in/HT210393#1331

**Comment by apphardtask** [comment]
@akshardarji However I am facing this in iOS 13.4.1 also.

What I did now is add a timer & call registration for push every 5 seconds and on success stop the timer.

This way, I am getting token however token is wrong. I need to check further. Will update once I get something.

Note : I am using Objective C code and not swift as this is old project.

**Comment by kas-kad** [comment]
@apphardtask did you try to that under cellular network?

**Comment by fparkar** [comment]
@kas-kad : Cellular works fine. Problem in WIFI only.

But to work with WIFI, I have to use NSTimer & keep on calling register token every 5 seconds.

**Comment by fparkar** [comment]
@akshardarji : However I am facing this in iOS 13.4.1 also.

What I did now is add a timer & call registration for push every 5 seconds and on success stop the timer.

This way, I am getting token however token is wrong. I need to check further. Will update once I get something.

Note : I am using Objective C code and not swift as this is old project.

**Comment by kas-kad** [comment]
Check with your network administrator https://support.apple.com/en-us/HT203609

**Comment by kas-kad** [comment]
@fparkar also, try one more thing: disable your timer, you don't need it for the experiment. 
1. Start the app
2. register for APNs token
3. if none received, stop the app, repeat from pt.1, this time you should receive the token.

**Comment by fparkar** [comment]
@kas-kad : "if none received, stop the app".. how? manually kill app you meant?

**Comment by kas-kad** [comment]
yes

**Comment by fparkar** [comment]
@kas-kad : I can't do that 1 by 1 to all my live users. This problem is coming on live also.

**Comment by kas-kad** [comment]
@fparkar what I've proposed is just an experiment, not a solution for production release.

**Comment by kas-kad** [comment]
@fparkar let me know about the results

**Comment by kas-kad** [comment]
@fparkar after you've done with the experiment. try to build your app for destribution (using Destribution Provisioning profile, either Ad-Hoc or AppStore). Does the registration perform well in such build config?

**Comment by fparkar** [comment]
@kas-kad : No, problem in live. So when I check with development mode, I found because token is not registered and hence push is not getting.

So I put logs and found that for iOS token is null and when I debug more I found push notification is not getting registered and hence token is not sent to server and hence push is not sent to the device.

**Comment by kas-kad** [comment]
@fparkar let me summarize, you don't get registration token (didRegisterForRemoteNotificationsWithDeviceToken not called) while under Wi-Fi and only under Wi-Fi, wheras under Cellular you have no issues. Also, you are able to workaround the issue by retrying the registration with timer. Is that correct?

**Comment by fparkar** [comment]
@kas-kad  : Yes.

Note : But one of my friend have mobile network. On live app he is also not getting push notification.
So saying notification not working on WIFI only is not 100% confirmed for me.
